import './globals.css'
import { Nunito } from 'next/font/google'
import Footer from './components/Footer'
import Providers from './components/Providers'
import TopBar from './components/Topbar'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='bg-[#F4F4F4]' suppressHydrationWarning={true}>
      <body>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GMAP_API_KEY}&libraries=places`}
        ></script>
        <Providers>
          <TopBar />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
